Repository nosqlbench/nosqlbench, pull requests merged in 2023-07, with the labels that each got.

#1375 Use further compression to logs & code coverage reports
  .github/workflows/build.yml
Labels: enhancement, easy pick

#1289 Bypass SSL validation option
  adapter-cqld4/src/main/resources/ssl.md
  engine-api/src/test/java/io/nosqlbench/engine/api/util/SSLKsFactoryTest.java
  nb-api/src/main/java/io/nosqlbench/api/engine/util/SSLKsFactory.java
Labels: enhancement

#1392 SignalPID() binding addition
  virtdata-lib-basics/src/main/java/io/nosqlbench/virtdata/library/basics/shared/unary_int/SignalPID.java
  virtdata-lib-basics/src/test/java/io/nosqlbench/virtdata/library/basics/tests/long_long/SignalPIDTest.java
Labels: enhancement

#1388 Snyk remediation 07.06.2023
  adapter-cqld4/pom.xml
  adapters-api/src/main/java/io/nosqlbench/engine/api/templating/StrInterpolator.java
  engine-api/pom.xml
  engine-docker/pom.xml
  engine-rest/pom.xml
  engine-rest/src/main/java/io/nosqlbench/engine/rest/resources/OpenApiEndpoint.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/resources/ScenarioExecutorEndpoint.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/resources/ServiceStatusEndpoint.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/resources/WorkloadFinderEndpoint.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/resources/WorkspacesEndpoint.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/services/WorkSpace.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/services/WorkspaceFinder.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/services/openapi/OpenApiLoader.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/services/openapi/OpenApiView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/services/openapi/PathOp.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/services/package-info.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/LiveScenarioView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/ProgressView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/ResultView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/RunScenarioRequest.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/WorkloadsView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/WorkspaceItemView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/WorkspaceView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/WorkspacesView.java
  engine-rest/src/main/java/io/nosqlbench/engine/rest/transfertypes/package-info.java
  engine-rest/src/main/resources/stargate.yaml
  engine-rest/src/test/java/io/nosqlbench/engine/rest/services/openapi/OpenApiLoaderTest.java
  engine-rest/src/test/resources/log4j2-test.xml
  mvn-defaults/pom.xml
  virtdata-api/pom.xml
Labels: security
